### ISSUE TITLE
Bluetooth doesn't work

### ISSUE THREAD

**Issue by xtomasnemec** [amervelic/Hackintosh-HP-Elitebook-850-G3-#1]
Mac OS detects the bluetooth module but it's not working and the bluetooth switch can't be switched on
![Screenshot 2023-04-13 at 12 35 16](https://user-images.githubusercontent.com/40271551/231733966-5c6a840e-9bb9-4a05-be2a-a0535945a612.png)
![Screenshot 2023-04-13 at 12 38 54](https://user-images.githubusercontent.com/40271551/231734353-e1633def-903e-484b-bc0d-53871631ecf3.png)

**Comment by amervelic** [comment]
![Screenshot 2023-04-17 at 20 10 27](https://user-images.githubusercontent.com/19406255/232573862-08b528aa-681d-4531-94b5-a5b5baf79f76.png)

**Comment by xtomasnemec** [comment]
I already fixed that
