### ISSUE TITLE
Sonoma support

### ISSUE THREAD

**Issue by xtomasnemec** [amervelic/Hackintosh-HP-Elitebook-850-G3-#2]
Hello i recently upgraded from Ventura Beta 13.5 to Sonoma Public Beta 1 and it upgraded without any problems. On boot (after login screen) it just crashes i enabled logging and the last thing in the log was `[EB|#LOG:EXITBS:START]` 
Thanks in advance

**Comment by amervelic** [comment]
Turn off AirPortItlwm because it is not supported on macOS 14 Sonoma. You can try using itlwm + Heliport.

**Comment by xtomasnemec** [comment]
It did not help
